# Generated by Django 5.0.2 on 2024-02-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='antonyms',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='definition',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='partOfSpeech',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='synonyms',
            field=models.TextField(default=''),
        ),
    ]
