# Generated by Django 5.0.2 on 2024-03-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='translated_meaning',
            field=models.TextField(default=''),
        ),
    ]
