# Generated by Django 5.0.2 on 2024-03-06 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_backend', '0002_searchhistory_translated_meaning'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchhistory',
            old_name='translated_meaning',
            new_name='translation',
        ),
    ]
